return {
	"saghen/blink.cmp",
  dependencies = { "rafamadriz/friendly-snippets" },
	version = "1.*",
	event = "VeryLazy",
	opts = {
		keymap = { preset = "enter" },
		appearance = {
			kind_icons = {
				Text = "",
				Method = "",
				Function = "ƒ",
				Constructor = "",
				Field = "",
				Variable = "",
				Property = "󰓹",
				Class = "",
				Interface = "",
				Struct = "",
				Module = "󰩦",
				Unit = "",
				Value = "",
				Enum = "",
				EnumMember = "",
				Keyword = "󰬴",
				Constant = "П",
				Snippet = "",
				Color = "",
				File = "",
				Reference = "",
				Folder = "",
				Event = "",
				Operator = "",
				TypeParameter = "Ţ",
			},
		},
		completion = {
			-- menu = { draw = { treesitter = { "lsp" } } },
			documentation = { auto_show = true, auto_show_delay_ms = 500 },
		},
		sources = {
			default = { "lsp", "path", "snippets", "buffer" },
		},
	},
	opts_extend = { "sources.default" },
}
